language: ruby
bundler_args: --without development
before_script:
  - psql -c 'create database kosynierzy_test;' -U postgres
  - cp config/database.sample.yml config/database.yml
  - cp config/application.sample.yml config/application.yml
  - bundle exec rake db:schema:load
script:
  - bundle exec rspec spec
rvm:
  - "2.0.0"
notifications:
  email:
    - yanoo@kosynierzy.info
addons:
  hosts:
    - kosynierzy.dev
    - wyjazdy.kosynierzy.dev
    - account.kosynierzy.dev
