APP_HOST: 'kosynierzy.dev'
SECRET_KEY_BASE: '6ee32cea59375e6cfdd033d3512e3a10'
GMAIL_USERNAME: "no-reply@kosynierzy.dev"
GMAIL_PASSWORD: password
CHILLOUT_SECRET: "secret"
DEVISE_SECRET_KEY: '6ee32cea59375e6cfdd033d3512e3a10'
